# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arrays.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 331)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.numberValue = QtWidgets.QSpinBox(self.centralwidget)
        self.numberValue.setGeometry(QtCore.QRect(20, 20, 41, 22))
        self.numberValue.setObjectName("numberValue")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(70, 20, 75, 23))
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtn.setObjectName("addBtn")
        self.removeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeBtn.setGeometry(QtCore.QRect(70, 110, 75, 23))
        self.removeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeBtn.setObjectName("removeBtn")
        self.orderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.orderBtn.setGeometry(QtCore.QRect(70, 80, 75, 23))
        self.orderBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orderBtn.setObjectName("orderBtn")
        self.resultList = QtWidgets.QListWidget(self.centralwidget)
        self.resultList.setGeometry(QtCore.QRect(170, 20, 141, 251))
        self.resultList.setObjectName("resultList")
        self.alterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.alterBtn.setGeometry(QtCore.QRect(70, 50, 75, 23))
        self.alterBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alterBtn.setObjectName("alterBtn")
        self.filterOptions = QtWidgets.QComboBox(self.centralwidget)
        self.filterOptions.setGeometry(QtCore.QRect(170, 280, 141, 22))
        self.filterOptions.setObjectName("filterOptions")
        self.filterOptions.addItem("")
        self.filterOptions.addItem("")
        self.filterOptions.addItem("")
        self.filterOptions.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arrays"))
        self.addBtn.setText(_translate("MainWindow", "Adicionar"))
        self.removeBtn.setText(_translate("MainWindow", "Remover"))
        self.orderBtn.setText(_translate("MainWindow", "Ordenar"))
        self.alterBtn.setText(_translate("MainWindow", "Alterar"))
        self.filterOptions.setItemText(0, _translate("MainWindow", "Exibir todos"))
        self.filterOptions.setItemText(1, _translate("MainWindow", "Pares"))
        self.filterOptions.setItemText(2, _translate("MainWindow", "Ímpares"))
        self.filterOptions.setItemText(3, _translate("MainWindow", "Quadrado perfeito"))
